@startuml
left to right direction

' Entidades principales
entity Usuario {
    + id : INTEGER(11) [PK]
    --
    nombre : VARCHAR(255)
    clave : VARCHAR(255)
    rol_id : INTEGER(11) [FK]
}

entity Rol {
    + id : INTEGER(11) [PK]
    --
    tipoRol : VARCHAR(255)
}

entity Permiso {
    + id : INTEGER(11) [PK]
    --
    nombre : VARCHAR(255)
}

entity Estudiante {
    + id : INTEGER(11) [PK]
    --
    nombre : VARCHAR(255)
    apellido : VARCHAR(255)
    usuario_id : INTEGER(11) [FK]
}

entity TematicaEstudio {
    + id : INTEGER(11) [PK]
    --
    estudiante_id : INTEGER(11) [FK]
    nombre : VARCHAR(255)
    descripcion : VARCHAR(255)
}

entity Mazo {
    + id : INTEGER(11) [PK]
    --
    nombre : VARCHAR(255)
    descripcion : VARCHAR(255)
    tematica_id : INTEGER(11) [FK]
    configurador_id : INTEGER(11) [FK]
}

entity Configurador {
    + id : INTEGER(11) [PK]
    --
    estudiante_id : INTEGER(11) [FK]
    intervaloInicial : VARCHAR(255)
    distanciaPorcentualIntervalo : DOUBLE
    coeficienteDeRetencion : DOUBLE
    bonusFacil : DOUBLE
    bonusDificil : DOUBLE
    intervaloMinimo : INTEGER(11)
    intervaloMaximo : INTEGER(11)
    umbralSanguijuelas : SMALLINT
    maximoDeNuevasCartas : SMALLINT
    maximoDeCartasARepasar : SMALLINT
    intervaloMaximoARevisarEnUnaSesion : INTEGER(11)
    intervaloParaIncluirMemoCardsNuevas : INTEGER(11)
}

entity MemoCard {
    + id : INTEGER(11) [PK]
    --
    nombre : VARCHAR(255)
    pregunta : VARCHAR(255)
    respuesta_id : INTEGER(11) [FK]
    fechaUltimoRepaso : DATETIME
    estadoMemoCard : EstadoMemoCard
    configurador_id : INTEGER(11) [FK]
    intervaloMinutos : INTEGER(11)
    cantidadDeOlvidos : SMALLINT
    intentos : SMALLINT
    esSanguijuela : BIT
    esNueva : BIT
    mazo_id : INTEGER(11) [FK]
}

entity EstadoMemoCard {
    + id : INTEGER(11) [PK]
    --
    tipo : VARCHAR(255) [Discriminador]
    nombre : VARCHAR(255)
    intervaloActual : INTEGER(11)
    rachaAciertos : SMALLINT
    rachaDesaciertos : SMALLINT
    umbralSanguijuela : SMALLINT
    coeficienteDeBonusPorFacilidad : DOUBLE
    coeficientePorDificultad : DOUBLE
    intervalos : VARCHAR(255) [Aprendizaje, Reaprendizaje]
    intervalosBonificados : VARCHAR(255) [Aprendizaje, Reaprendizaje]
    bonificacionTotal : DOUBLE [Aprendizaje, Reaprendizaje]
    distanciaPorcentualIntervalo : DOUBLE [Reaprendizaje]
    intervaloMin : INTEGER(11) [Reaprendizaje]
    coeficienteDeRetencion : DOUBLE [Repaso]
    intervaloMax : INTEGER(11) [Repaso]
}

entity RespuestaMemo {
    + id : INTEGER(11) [PK]
    --
    texto : VARCHAR(255)
    rutaImagen : VARCHAR(255)
    rutaAudio : VARCHAR(255)
    rutaVideo : VARCHAR(255)
}

entity SesionDeEstudio {
    + id : INTEGER(11) [PK]
    --
    estudiante_id : INTEGER(11) [FK]
    mazo_id : INTEGER(11) [FK]
    tiempoEstudio : INTEGER(11)
    cantidadTotalIntentos : SMALLINT
    cantidadTotalAciertos : SMALLINT
    cantidadTotalDesaciertos : SMALLINT
    cantidadTotalDificil : SMALLINT
    cantidadTotalBien : SMALLINT
    cantidadTotalFacil : SMALLINT
    fechaInicio : DATETIME
    fechaFin : DATETIME
    estaFinalizada : BIT
}

entity HistorialEstadoMemoCard {
    + id : INTEGER(11) [PK]
    --
    memoCard_id : INTEGER(11) [FK]
    estadoAnterior : EstadoMemoCard  [FK]
    estadoNuevo : EstadoMemoCard  [FK]
    fechaCambio : DATETIME
}

' Relaciones
Usuario }|--|| Rol
Rol ||--o{ Permiso
Estudiante }|--|| Usuario
Estudiante ||--|{ TematicaEstudio
TematicaEstudio ||--o{ Mazo
Mazo }|--|| Configurador
Mazo ||--o{ MemoCard
MemoCard ||--o| RespuestaMemo
MemoCard }|--|| Configurador
MemoCard ||--o{ HistorialEstadoMemoCard
MemoCard }|--|| EstadoMemoCard
HistorialEstadoMemoCard }|--|| EstadoMemoCard : estadoAnterior
HistorialEstadoMemoCard }|--|| EstadoMemoCard : estadoNuevo
SesionDeEstudio }|--|| Estudiante
SesionDeEstudio }|--|| Mazo
SesionDeEstudio ||--o{ MemoCard

@enduml